### ISSUE TITLE
Incorrect?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/yarn-global-modules#1]
It's correct, mostly. Except that in that global directory there is `node_modules` and package.json. That's the very cool thing that i like in Yarn. Global is built just the same way as any other package with dependencies, which in that case are globally installed modules.

So, for consistency with `global-modules` which gives you directly path to where the installed modules are, we should join `node_modules` too.

Thoughts? @doowb @jonschlinkert

**Comment by jonschlinkert** [comment]
IMHO the user should do what you're suggesting. This library provides the same global path that yarn uses "under the hood".
